### ISSUE TITLE
Advice: Add a section about the difference between our final implementation and the v3-core&v3-periphery repo

### ISSUE THREAD

**Issue by y1cunhui** [Jeiwan/uniswapv3-book#39]
After following the whole book, I can almost understand all the code in the uniswapv3-code repo. But when reading the real uniswap v3 code repo, I found there is still some difference between it and our implementation, and there are some contracts we don't have(like V3Migrate, MultiCall, PeripheryPaymentWithFee, difference between QuoterV1&V2... etc.) 

I'm wondering if it's convenient to add a section about the structure of the real V3 contracts, some contracts we do not have and their function, analyze some real transactions on Uniswap V3, etc. This would bring us closer to the real-world.

(And I know the repo is just for learning and not ready for deployment in real world. So maybe want some advice about wahat else we need to do&consider to make it a real system?)

**Comment by Jeiwan** [comment]
That's a great idea! I'll extend the introduction with a detailed overview of the contracts that will be implemented in the book and how they differ from the original implementation.

Yeah, the book doesn't implement a complete clone of Uniswap V3 because Uniswap is a big project and explaining (let alone implementing!) all the mechanics is quite a big task that will make the book too big. My goal was to explain the core mechanisms (swapping, fees, wrapper contracts, NFTs) since they are the most important and difficult pieces of Uniswap. I expect that reader will be able to figure all the other things out by themselves after reading the book.

**Comment by Jeiwan** [comment]
Added a chapter to the introduction:
https://uniswapv3book.com/docs/introduction/what-we-will-build/

@y1cunhui let me know if you think there's something to improve.
